SET IDENTITY_INSERT PARADM_COMPANY ON;
INSERT INTO PARADM_COMPANY(ID,COMPANY_NAME,COMPANY_NAME_ENG,CODE,OWNER_ID,ADDRESS1,ADDRESS2,ADDRESS3,CITY,[STATE],POSTAL_CODE,AREA_CODE,PHONE_NO,
                           FAX_NO,URL,EMAIL,COUNTRY_ID,PROVINCE_ID,LEAD_SOURCE_ID,INDUSTRY_ID,TURNOVER,EMPLOYEE_COUNT,STOCK_CODE,BUSINESS_ACTIVITY,
                           BACKGROUND,USER_DEF_1,USER_DEF_2,USER_DEF_3,USER_DEF_4,USER_DEF_5,SPECIAL_ALERT_ID,CLASS_TYPE,CIC_ID,SIC_ID,STATUS_ID,
                           OVERSEAS_BRANCHES,HK_BRANCHES,DS_DB_NAME,DS_DB_TYPE,DS_DRIVER_CLASS,DS_URL,DS_USERNAME,DS_PWD,DS_JNDI_NAME,
                           DS_AUTO_COMMIT,DS_READ_ONLY,DS_MAX_ACTIVE,DS_MAX_IDLE,DS_MAX_WAIT,DS_POOL_PS,DS_MAX_OPEN_PS,DS_TRANSACTION_ISOLATION,
                           DS_LOG_ABANDONED,DS_REMOVE_ABANDONED,DS_WHILE_IDLE,ACTIVE_FLAG,EXPIRE_DATE,REMIND_DATE,COMPLETE_INIT,CONFIGURING_PERCENT,
                           LICENSED_USER,STORAGE_SPACE,IS_CLOUD,STORAGE_TYPE,RECORD_STATUS, UPDATE_COUNT, CREATOR_ID, CREATE_DATE, UPDATER_ID, UPDATE_DATE)
VALUES (10000,'Co. Ltd.','Co. Ltd.','',10000,'','','','','','','','',
        '','','',0,0,NULL,NULL,NULL,NULL,NULL,NULL,
        NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
        NULL,NULL,'BIZ_10000',0,'com.microsoft.sqlserver.jdbc.SQLServerDriver','jdbc:sqlserver://127.0.0.1:1433;databaseName=BIZ_10000','sa','P@ssw0rd',NULL,
        'false','false',60,3,5000,'true',500,1,
        'true','true','true',2,'2099-12-31 00:00:00.000',NULL,1,0,
        30,500,1,3,0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT PARADM_COMPANY OFF;

SET IDENTITY_INSERT USER_GROUP ON;
INSERT INTO USER_GROUP(ID,OWNER_USER_RECORD_ID,GROUP_TYPE,GROUP_NAME,GROUP_DESC,PARENT_GROUP_ID,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES(-1,0,0,'All internal users',null,null,0,0,0,GETDATE(),0,GETDATE());
SET IDENTITY_INSERT USER_GROUP OFF;

SET IDENTITY_INSERT USER_ROLE ON;
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10000,0,'user.label.role.type.admin','administrator',0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10001,1,'user.label.role.type.user','internal user',0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10002,2,'user.label.role.type.external.user','external user',0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT USER_ROLE OFF;

SET IDENTITY_INSERT USER_RULES ON;
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES(-1,-1,1,0,0,0,GETDATE(),0,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10000,10000,2,0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10001,10001,2,0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10002,10002,2,0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT USER_RULES OFF;

SET IDENTITY_INSERT SYS_PARAMETER ON;
INSERT INTO SYS_PARAMETER(ID,PARAMETER_CODE,PARAMETER_VALUE,PARAMETER_DEFAULT_VALUE,PARAMETER_TYPE,DESCRIPTION,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE,STATUS)
VALUES (1000, 'app.base.url', '', 'http://127.0.0.1:8080/', 0, '', 0, 0, 10000, GETDATE(), 10000, GETDATE(),1);
INSERT INTO SYS_PARAMETER(ID,PARAMETER_CODE,PARAMETER_VALUE,PARAMETER_DEFAULT_VALUE,PARAMETER_TYPE,DESCRIPTION,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE,STATUS)
VALUES (1001, 'db.date.format', 'yyyy-MM-dd HH:mm', 'yyyy-MM-dd HH:mm', 0, 'Default date format.', 0, 0, 10000, GETDATE(), 10000, GETDATE(),0);
SET IDENTITY_INSERT SYS_PARAMETER OFF;

SET IDENTITY_INSERT SYS_FUNCTION ON;
-- root sys-function
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (10000,'DMS','system.label.dms','',0,'/dms/company/list',100,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (20000,'SHARING','system.label.sharing','',0,'/share/sharing/list',200,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (30000,'AUTOMATION','system.label.automation','',0,'/automation/record/list?automation',300,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (40000,'ADMIN','system.label.admin','',0,'/admin/dashboard/list?admin',400,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (50000,'WOLF','system.label.wolf','',0,'/wolf/dashboard/list?wolf',500,0,'RE',0);

-- first sys-function
SET IDENTITY_INSERT SYS_FUNCTION OFF;

SET IDENTITY_INSERT SMARTSHARE_LOC_MASTER ON;
INSERT INTO SMARTSHARE_LOC_MASTER(ID,LOC_NAME,LOC_PATH,SEGMENT_NO,DESCRIPTION,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10000,'Default','/usr/SmartShare/file',0,'The physical data storage location',0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT SMARTSHARE_LOC_MASTER OFF;
