SET IDENTITY_INSERT USER_GROUP ON;
INSERT INTO USER_GROUP(ID,OWNER_USER_RECORD_ID,GROUP_TYPE,GROUP_NAME,GROUP_DESC,PARENT_GROUP_ID,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES(-1,0,0,'All internal users',null,null,0,0,0,GETDATE(),0,GETDATE());
SET IDENTITY_INSERT USER_GROUP OFF;

SET IDENTITY_INSERT USER_ROLE ON;
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10000,0,'user.label.role.type.admin','administrator',0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10001,1,'user.label.role.type.user','internal user',0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_ROLE(ID,ROLE_TYPE,ROLE_NAME,ROLE_DESC,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10002,2,'user.label.role.type.external.user','external user',0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT USER_ROLE OFF;

SET IDENTITY_INSERT USER_RULES ON;
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES(-1,-1,1,0,0,0,GETDATE(),0,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10000,10000,2,0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10001,10001,2,0,0,10000,GETDATE(),10000,GETDATE());
INSERT INTO USER_RULES(ID,OBJECT_ID,RULES_TYPE,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE)
VALUES (10002,10002,2,0,0,10000,GETDATE(),10000,GETDATE());
SET IDENTITY_INSERT USER_RULES OFF;

SET IDENTITY_INSERT SYS_PARAMETER ON;
INSERT INTO SYS_PARAMETER(ID,PARAMETER_CODE,PARAMETER_VALUE,PARAMETER_DEFAULT_VALUE,PARAMETER_TYPE,DESCRIPTION,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE,STATUS)
VALUES (1000, 'app.base.url', '', 'http://127.0.0.1:8080/', 0, '', 0, 0, 10000, GETDATE(), 10000, GETDATE(),1);
INSERT INTO SYS_PARAMETER(ID,PARAMETER_CODE,PARAMETER_VALUE,PARAMETER_DEFAULT_VALUE,PARAMETER_TYPE,DESCRIPTION,RECORD_STATUS,UPDATE_COUNT,CREATOR_ID,CREATE_DATE,UPDATER_ID,UPDATE_DATE,STATUS)
VALUES (1001, 'db.date.format', 'yyyy-MM-dd HH:mm', 'yyyy-MM-dd HH:mm', 0, 'Default date format.', 0, 0, 10000, GETDATE(), 10000, GETDATE(),0);
SET IDENTITY_INSERT SYS_PARAMETER OFF;

SET IDENTITY_INSERT SYS_FUNCTION ON;
-- root sys-function
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (10000,'DMS','system.label.dms','',0,'/dms/company/list',100,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (20000,'SHARING','system.label.sharing','',0,'/share/sharing/list',200,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (30000,'AUTOMATION','system.label.automation','',0,'/automation/record/list?automation',300,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (40000,'ADMIN','system.label.admin','',0,'/admin/dashboard/list?admin',400,0,'RE',0);
INSERT INTO SYS_FUNCTION(ID,FUNCTION_CODE,FUNCTION_LABEL,FUNCTION_ICON,PARENT_ID,LINK_URL,DISPLAY_SEQ,MENU_TYPE,PERMISSION_TYPE,STATUS)
VALUES (50000,'WOLF','system.label.wolf','',0,'/wolf/dashboard/list?wolf',500,0,'RE',0);

-- first sys-function
SET IDENTITY_INSERT SYS_FUNCTION OFF;

