server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**
  messages:
    basename: i18n/messages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      url: jdbc:sqlserver://mssql.paradm.com:1433;databaseName=SSE-Dev
      username: sa
      password: Bj4dhva3HctuR4D2jzhSRVsHt7Rf1V9pHUufqnpb5++NgS3Tx1j1fv7uT4e+efKJn3v3D9oVLq70BzXnNxwXQg==
      filters: config,stat,wall
      connection-properties: config.file=classpath:druid-pool.properties;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      webStatFilter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      statViewServlet:
        enabled: true
        loginUsername: druid
        loginPassword: druid123
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
  jpa:
    generate-ddl: false
    show-sql: false
    database: sql_server
    database-platform: com.paradm.sse.framework.dialect.ParadmSQLServerDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  customize:
    security:
      csrf-ignore-url: /api/**,/druid/**
      static-ignore-url: /theme/**,/js/**,/webjars/**
      permit-all: /kaptcha/**,/druid/**,/api/**,/,/index,/init/**
      browser:
        login-page: /login
        logout-url: /logout
