spring:
  application:
    name: sse-business
  profiles:
    active: dev
  kaptcha:
    enabled: true
    properties:
      border:
        enabled: false
        color: "105,179,90"
      noise:
        impl: "com.google.code.kaptcha.impl.NoNoise"
      obscurificator:
        impl: "com.paradm.kaptcha.impl.NoDistortion"
      text-producer:
        character:
          string: "0123456789"
          length: 4
          space: 2
        font:
          size: 14
          color: "98,98,98"
          names: "Arial"
      background:
        clear-from: "238,238,238"
        clear-to: "238,238,238"
      image:
        width: 36
        height: 15
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
